repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.1
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        args: ["--application-directories=.:fluidspylib", --py38-plus]
